In [4]:
import numpy as np
import os

In [44]:
# data_target = np.zeros((1,3500))
# data_target = np.arange(3500).reshape(1,3500)

# for i in range(3500):
#     if i < 700:
#         data_target[i] = 1
#     elif i < 1400:
#         data_target[i] = 2
#     elif i < 2100:
#         data_target[i] = 3
#     elif i < 2800:
#         data_target[i] = 4
#     else:
#         data_target[i] = 5    
# data_target[0,1] = 1    
# data_target[1] = 3
data_target = np.array([1])
print(data_target)
for i in range(3499):
    if i<699:
        data_target = np.concatenate((data_target, [1]), axis=None)
    elif i<1399:
        data_target = np.concatenate((data_target, [2]), axis=None)
    elif i<2099:
        data_target = np.concatenate((data_target, [3]), axis=None)
    elif i<2799:
        data_target = np.concatenate((data_target, [4]), axis=None)
    else:
        data_target = np.concatenate((data_target, [5]), axis=None)
print(data_target)


[1]
[1 1 1 ... 5 5 5]


In [45]:
path = "data_hog/data_hog.txt"
data_hog = np.loadtxt(path)
# print(data_hog)
# data_hog = np.concatenate((data_hog, data_target), axis=1)
# print(data_hog[1, :])

In [16]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [46]:
X = data_hog
y = data_target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
print(X_train)
print(y_train)

[[0.12466708 0.00473014 0.0023114  ... 0.00556215 0.00463806 0.09836366]
 [0.01516582 0.07605877 0.00721252 ... 0.01759311 0.05954144 0.05149384]
 [0.04964189 0.02304126 0.00190664 ... 0.03242863 0.07323346 0.05822062]
 ...
 [0.00268668 0.00349665 0.02242162 ... 0.00170527 0.30973231 0.01141008]
 [0.00377552 0.0070034  0.         ... 0.0126875  0.00102169 0.01388678]
 [0.         0.         0.00227131 ... 0.00442917 0.0015681  0.        ]]
[1 2 3 ... 2 2 5]


In [47]:
model_svm = SVC(gamma='auto')
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [48]:
print (f'Accuracy - : {model_svm.score(X_train,y_train):.3f}')

Accuracy - : 0.207
